### ISSUE TITLE
Mapping parameter names passed to ResourceKit::ActionInvoker 

### ISSUE THREAD

**Issue by lancefrench** [digitalocean/resource_kit#14]
I'm still noodling the most elegant way to add this functionality, but I wanted to create an issue in case you had any ideas.  I would like to map `Action` argument names in the same way that Kartograph allows mapping of key values for API responses to more idiomatic ruby-style names.

For example, in our mapping: 
`Kartograph::DSL` populates `Customer.customer_id` based on an JSON key of `customerID` thus making the `Customer` object more ruby friendly.  

Sadly, the API endpoints I am working with use these non-ruby style keys as `query_params` which requires the following:

`client.customers.find(customerID: 1)`  rather than `client.customers.find(customer_id: 1)`

Consider this a more general issue than supporting a singular `find` on a resource that could be performed by constructing the `path` directly.  Just a generic case where you have `*args` you want to map to `query_keys` with different symbol names.  For example:

``` ruby
resources do
  action :all do
  verb :get
  path '/API/Account/:account_id/Customer.json'
  param_mapping { :customer_type_id => :customerTypeID, :time_stamp => :timeStamp }
  query_keys :limit, :offset, :customerTypeID, :timeStamp
  handler(200) {|response| CustomerMapping.extract_collection(response.body, :read) }
end
```

`param_mapping` would be fed to a helper method on `ActionInvoker` to rekey the passed in `@options`.  Using something like [Facets](https://github.com/rubyworks/facets/blob/master/lib/core/facets/hash/rekey.rb) would make implementation easy, but it still feels hacky to me.  I will submit a pull request if I come up with anything good.

**Comment by bobbytables** [comment]
Hi @lancefrench!

I think what I would prefer to see is just an extension of the functionality in `query_keys`, and allow both. Ruby's syntax would allow this to still look elegant:

```ruby
query_keys, :limit, :offset, customerTypeId: :customer_type_id
```

Or the reverse of the hash would make sense as well. Either way, thoughts on that?

**Comment by lancefrench** [comment]
That would work.  I didn't really think about extending query_keys.  In my mind, I would love to include this under mappings but I am unlikely to submit a patch of that scope.  Let me take a look at it over the weekend and see if I can come up with something.

**Comment by lancefrench** [comment]
Ok, here's what I have for the happy path case.  Inside `ResourceKit::EndpointResolver` we have access to both the `query_keys` and the `values` being passed in to `resolve()`.  With these, we should be able to create a mapping using any query_key that is of type Hash.  For example:

```ruby
query_param_keys = [:limit, :offset, {:customer_type_id=>:customerTypeId}]
values = {customer_type_id: 1}

mappings = {}

query_param_keys.each do |obj|
  if obj.is_a?(Hash) then
    # Add our hash to a mapping array for later use with the values hash  
    mappings.merge!(obj)
    # Replace the hash in query params with the mapped value
    query_param_keys[query_param_keys.index(obj)] = obj.values[0]    
  end  
end  

# Replace the original value key with our mapped version.
values = Hash[values.map {|k,v| [mappings[k], v] }]
```

Do you have any suggestions on organizing this code within `ResourceKit::EndpointResolver`?  Does this seem like an acceptable solution?

**Comment by lancefrench** [comment]
Closing out old issues that I will not be revisiting.  This was in service of responses from the Lightspeed POS API.
