### ISSUE TITLE
Add failure message to the tests matchers

### ISSUE THREAD

**Issue by vjustov** [digitalocean/resource_kit#17]
When using the test helpers, rspec complains that the HaveActionMatchers and the ActionHandlerMatchers neither have a failure_message method defined. This is a bit misleading and requires rspec knowledge to understand whats going on.

```
Failure/Error: expect(described_class).to have_action(:find).that_handles(:ok).at_path('/api/v1/shoppers')
     NoMethodError:
       undefined method `failure_message' for #<ResourceKit::Testing::HaveActionMatchers:0x007f89334343d8>
```

**Comment by bobbytables** [comment]
Yeah this is definitely something I overlooked when I wrote those. :disappointed:

**Comment by vjustov** [comment]
I'm taking a look at them, to see if i can submit a PR.
