### ISSUE TITLE
update addressable dependency

### ISSUE THREAD

**Issue by rmoriz** [digitalocean/resource_kit#29]
Hi,

resource_kit still requires a `2.3.x` version of `addressable`. Other projects, like Chef, already moved to the latest `2.4.0` release which causes incompatibilities using `droplet_kit`.

see: 

https://github.com/rmoriz/knife-digital_ocean/issues/89
https://github.com/chef/chef-dk/blob/master/Gemfile.lock#L124

**Comment by phillbaker** [comment]
Thanks @rmoriz mind doing a quick PR to update the gemspec? Probably `"<= 3.0.0"` would be good to make this easier in the future.
